services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: appdb
    ports:
      - "55432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
